name: Build and Deploy StenfordCeramicsAPI to VPS

on:
  push:
    branches:
      - release
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u shreyanspadmani --password-stdin

      - name: Build and Push Docker image to ECR
        run: |
          docker build -t uniqueitsolution/stenford_ceramics_api:latest .
          docker push uniqueitsolution/stenford_ceramics_api:latest

      - name: Restart StenfordCeramicsAPI service on Hostinger VPS
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo systemctl restart stenfordceramicsapi.service
            sudo docker image prune -f
            docker rm $(docker ps -a -q -f status=exited -f status=created -f status=paused) || true
